add_newline = true
command_timeout = 200
format = "[$username$hostname$directory$git_branch$git_status]($style)$character"

[character]
error_symbol = "[✗](bold red)"
success_symbol = "[➜](bold green)"

[username]
show_always = true
style_user = "fg:#f1184c"
style_root = "bg:#9A348E"
format = '[$user]($style)'
disabled = false

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue) [$hostname ](bold yellow)'
disabled = false

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold green"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
style = "bold green"

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

